### ISSUE TITLE
Ada bug yang buat job list gak nampilan job2 dari halaman berikutnya

### ISSUE THREAD

**Issue by arga-saragih-runchise** [unpraditable/job-portal-node#1]
Langkah2 utk repro:
1. Pas pertama buka halaman list, langsung klik 'Search'
2. Klik 'See More'
3. Daftar job gak berubah (padahal klo di cek di Dev Tools, sudah hit API utk halaman ke2 dan ada data job nya)

Saranku sih jangan pakai 2 state berbeda utk simpen list jobs nya. Pakai 1 state aja, mungkin yg `filteredJobs` bisa dihapus aja.
Heheh thanks again for applying to Runchise

**Comment by unpraditable** [comment]
@arga-saragih-runchise halooo, makasih banyak udah komen, hehehe. 

Iya sebenernya ini repo buat aku belajar Node setelah sekian lama gak nyentuh juga sama sekaligus task interview sebagai fullstack engineer di sebuah company, kemarin aku udah notice ada bug ini juga dan nyadar juga kalau gak perlu `filteredJobs`, tapi kemarin pas notice ini bug udah mepet banget deadline dan sampai sekarang aku belum sempet perbaikin ini juga, hehehe.

Makasih banyak masukannya mas 🙇 . 

Sama2, mudah2an bisa kerja sama dengan bareng kalau aku diterima nanti, mudah2an yang terbaik 🙇

**Comment by arga-saragih-runchise** [comment]
Oke, kita close aja ya issue nya biar bersih repo nya
